### ISSUE TITLE
Fresh deployed ova freezes on first boot

### ISSUE THREAD

**Issue by dcasota** [guarddog-dev/VMware_Photon_OVA#1]
Hi Russel,

A strange effect when deploying the downloaded photontce.guarddog.lab-0.12.1.ova is that it doesn't get configured to the finish.
In step "Cleaning up Repo Download" it freezes (?).

![image](https://user-images.githubusercontent.com/14890243/194313149-942b127f-7b01-4512-9925-d678ccc87f01.png)

After a cold reset the vm bios doesn't recognize the boot media.

Any idea?

**Comment by RussellHamker** [comment]
This means that the OVA did not get an IP address. Change the OVAs network settings to resolve.

**Comment by dcasota** [comment]
very rare case -> close
